version: "3"
services:
  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  server:
    build: ./server
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      DATABASE_HOST: postgres
  client:
    build: ./client
    ports:
      - '8080:3000'
    depends_on:
      - server
    environment:
      API_HOST: server
